### ISSUE TITLE
github workflows - rename 'target' to github environment

### ISSUE THREAD

**Issue by julie-ng** [julie-ng/cloud-architecture-review#7]
### Problem

Right now we have

```yaml
on:
  workflow_call:
    outputs:
      target:
        description: 'GitHub Environment for deployment'
        value: ${{ jobs.setup-variables.outputs.target }}
```

and it's not clear that `target` refers to a [GitHub Environment boundary](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment)

```yaml
on:
  # ...
  jobs:
    # Dev
    # ===
    - id: is-dev
      if: github.ref == 'refs/heads/aks-architect/main' # <== CONFIGURE (1)
      name: 'DEV: set vars'
      run: |
        echo "target=aks-architect-dev" >> $GITHUB_ENV
```

### Solution

Rename `target` to `github-environment`
